from .ipa import jyutping_to_ipa as jyutping_to_ipa

__version__: str
__all__: list[str]

class Pipeline:
    def __init__(self, *, punc_norm: bool = True) -> None: ...
    def convert(self, text: str) -> str: ...
    def convert_batch(self, texts: list[str]) -> list[str]: ...
    def convert_detailed(self, text: str) -> list[tuple[str, str, str]]: ...
    def convert_ipa(self, text: str, tone: str = "diacritic") -> str: ...
