from .ipa import jyutping_to_ipa as jyutping_to_ipa
from .phonology import Inventory as Inventory
from .phonology import Syllable as Syllable
from .phonology import inventory as inventory
from .phonology import segment as segment

__version__: str
__all__: list[str]

class Pipeline:
    def __init__(
        self, *, punc_norm: bool = True, user_dict: dict[str, str] | None = None
    ) -> None: ...
    def convert(self, text: str) -> str: ...
    def convert_batch(self, texts: list[str]) -> list[str]: ...
    def convert_detailed(self, text: str) -> list[tuple[str, str, str]]: ...
    def convert_candidates(self, text: str) -> list[tuple[str, list[str], str]]: ...
    def convert_candidates_batch(
        self, texts: list[str]
    ) -> list[list[tuple[str, list[str], str]]]: ...
    def convert_ipa(self, text: str, tone: str = "diacritic") -> str: ...
