class PyPipeline:
    def __init__(
        self,
        punc_norm: bool = True,
        data_dir: str | None = None,
        user_dict: dict[str, str] | None = None,
    ) -> None: ...
    @staticmethod
    def from_dir(dir: str, punc_norm: bool = True) -> PyPipeline: ...
    def convert(self, text: str) -> str: ...
    def convert_batch(self, texts: list[str]) -> list[str]: ...
    def convert_detailed(self, text: str) -> list[tuple[str, str, str]]: ...
    def convert_candidates(self, text: str) -> list[tuple[str, list[str], str]]: ...
    def convert_candidates_batch(
        self, texts: list[str]
    ) -> list[list[tuple[str, list[str], str]]]: ...
    def convert_candidates_scored(
        self, text: str
    ) -> list[tuple[str, list[str], str, str]]: ...
    def convert_candidates_scored_batch(
        self, texts: list[str]
    ) -> list[list[tuple[str, list[str], str, str]]]: ...
