class PyPipeline:
    def __init__(self, punc_norm: bool = True) -> None: ...
    @staticmethod
    def from_dir(dir: str) -> PyPipeline: ...
    def convert(self, text: str) -> str: ...
    def convert_batch(self, texts: list[str]) -> list[str]: ...
    def convert_detailed(self, text: str) -> list[tuple[str, str, str]]: ...
