class PyPipeline:
    def __init__(self) -> None: ...
    def convert(self, text: str) -> str: ...
    def convert_batch(self, texts: list[str]) -> list[str]: ...
    def convert_detailed(self, text: str) -> list[tuple[str, str, str]]: ...
